[package]
name = "exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry = { version = "0.31.0" }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
sqlx = "0.8.6"
opentelemetry-otlp = { version = "0.31.0", features = [
    "grpc-tonic",
    "tls-roots",
] }
hyper = "1.6.0"
tokio = "1.45.1"
log = "0.4.27"
base64 = "0.22.1"
