[workspace]
members = [
    "configuration",
    "engine",
    "exporter", 
    "discovery", 
    "probe",
]

[package]
name = "zookoo"
version = "0.0.2"
edition = "2024"

license = "MIT OR Apache-2.0"

[dependencies]
configuration = { path = "configuration" }
engine = { path = "engine" }
exporter = { path = "exporter" }
env_logger = "0.11.8"
env = "1.0.1"
dotenvy = "0.15.7"
log = "0.4.27"
clap = { version = "4.5.40", features = ["derive", "env"] }
tokio = "1.52.3"
pyroscope = { version = "2.0.3", features = ["backend-pprof-rs"] }
hostname = "0.4.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2.0"
opentelemetry = "0.31.0"
opentelemetry-stdout = { features = ["logs"], version = "0.32.0"}
opentelemetry_sdk = { features = ["logs"], version = "0.31.0"}
tracing-opentelemetry = "0.32.0"
opentelemetry-appender-tracing = "0.31.1"
opentelemetry-otlp = { version = "0.31.0", features = ["http-proto", "logs"] }
base64 = "0.22.1"
