[exporter.otlp]
url = "http://localhost:8080"
skip_tls_verify = true

[exporter.otlp.auth]
user = "user"
password = "password"

[exporter.metrics]
enpoint = "/metrics"

[exporter.kafka]
broker = "localhost:9092"
topic = "metrics"

[http]
database = [
    { conn_string = "postgresql://user:password@localhost:5432/dbname" },
]

target_file = ["targets.json"]
targets = [
    { url = "https://google.com/", labels = [
        { "env" = "test" },
    ], scrap_interval = "5s", follow_redirects = true },
]
