{
 "title": "Zookoo - HTTP",
 "tags": [
  "zookoo",
  "http"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(probe_target_up,service_name)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(probe_target_up,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(probe_target_up{job=\"$job\", service_name=\"$service_name\", probe=\"http\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Probe Status ${instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Instance availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(latitude, longitude) (probe_target_up{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe availability map - ${instance}",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg by(latitude, longitude, probe, probe_zone) (probe_target_up{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance probe success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(latitude, longitude) (probe_target_success{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_request_duration_milliseconds{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificate begin date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_cert_begin_ts{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Certificate expiration date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_cert_expiration_ts{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "HTTP ${instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "instance" },
  {
   "title": "Http duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance) (probe_http_request_duration_milliseconds {service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "total_request_duration"
    },
    {
     "expr": "sum by (instance) (probe_dns_lookup_duration_milliseconds{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "dns_lookup_duration"
    },
    {
     "expr": "sum by (instance) (probe_http_tls_handshake_duration_milliseconds{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "tls_handshake_duration"
    },
    {
     "expr": "sum by (instance) (probe_http_tls_lookup_duration_milliseconds{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "tls_duration"
    }
   ]
  },
  {
   "title": "Request duration repartition",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(probe_dns_lookup_duration_milliseconds_bucket{service_name=\"$service_name\", job=\"$job\", instance=~\"$instance\"}[2m])) by (le))",
     "legendFormat": "duration"
    }
   ]
  }
 ]
}