{
 "title": "Zookoo - ICMP",
 "tags": [
  "zookoo",
  "icmp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(probe_target_up,service_name)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(probe_target_up,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(probe_target_up{job=\"$job\", service_name=\"$service_name\", probe=\"icmp\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Probe Status ${instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Instance availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(latitude, longitude) (probe_target_up{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe availability map - ${instance}",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg by(latitude, longitude, probe, probe_zone) (probe_target_up{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance probe success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(latitude, longitude) (probe_target_success{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_request_duration_milliseconds{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ICMP ${instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "instance" },
  {
   "title": "ICMP duration - ${instance}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_ping_duration_milliseconds{service_name=~\"$service_name\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "ping_duration"
    }
   ]
  }
 ]
}