//! # Exporter crate
//!
//! This crate is responsible of the export of the differents metrics generated by the probes.
//!
//! ## Exporter type
//!
//! - Open telemetry
//! - Prometheus Pushgateway
//!

use std::collections::HashMap;

use configuration::model::Configuration;

use crate::types::{ExportersMap, ProbeType};

pub mod config;
mod labels;
pub mod otel;
pub mod prom;
pub mod timescale;
pub mod types;

#[cfg(test)]
mod config_tests;

pub trait Exporter: Send + Sync {
    /// Build the exporter.
    fn build(config: &Configuration, exporters: &mut ExportersMap)
    where
        Self: Sized;

    /// Export metrics for a given probe type.
    fn export(&self, probe_type: ProbeType, metric_data: MetricData);
}

/// Metric data containing both numeric metrics and string labels from targets
#[derive(Debug, Clone)]
pub struct MetricData {
    /// Numeric metric values (e.g., duration_ms, status_code)
    pub metrics: HashMap<String, isize>,
    /// String labels from the target configuration (e.g., service, env)
    pub labels: HashMap<String, String>,
}

impl MetricData {
    pub fn new() -> Self {
        MetricData { metrics: HashMap::new(), labels: HashMap::new() }
    }

    pub fn with_metrics(metrics: HashMap<String, isize>) -> Self {
        MetricData { metrics, labels: HashMap::new() }
    }

    pub fn with_labels(mut self, labels: HashMap<String, String>) -> Self {
        self.labels = labels;
        self
    }

    pub fn with_instance(mut self, instance: String) -> Self {
        self.labels.insert("instance".to_string(), instance);
        self
    }

    pub fn with_probe(mut self, probe: ProbeType) -> Self {
        self.labels.insert("probe".to_string(), probe.to_string());
        self
    }
}

impl Default for MetricData {
    fn default() -> Self {
        Self::new()
    }
}

pub fn build_exporters(config: &Configuration, exporters: &mut ExportersMap) {
    if config.exporter.is_none() {
        log::error!("event=error msg=no_exporters_configured");
        panic!("No exporters configured, exiting...");
    }

    otel::exporter::OtelExporter::build(config, exporters);
    prom::PrometheusRemoteWriteExporter::build(config, exporters);
    timescale::TimescaleExporter::build(config, exporters);
}
