//! # Exporter crate
//!
//! This crate is responsible of the export of the differents metrics generated by the probes.
//!
//! ## Exporter type
//!
//! - Open telemetry
//!

use std::{collections::HashMap, io::Error};

pub mod config;
pub mod otel;

#[derive(Debug)]
pub struct ExporterRequest {
    pub exporter: ExporterConfigurationRequest,
    pub metrics: HashMap<String, isize>,
}

#[derive(Debug)]
pub struct ExporterConfigurationRequest {}

pub trait Export {
    fn export(&self, data: ExporterRequest) -> Result<(), Error>;
}
